var amor= window.prompt("lo que siempre debes dar como Dios nos ama");
var respeto = ("merecemos todos");
var compromiso = ("lo que debemos tener con lo que hacemos diariamente");


if(amor=="nunca de acaba"){

}else if(amor  == "verdadero"){

}else if(topping == "brownie"){
precio = 0.75;
}else  if(topping == "lacasitos"){
precio = 0.95;
}else{
document.write("no tenemos este topping, lo sentimos. ");
precio = 0;
}
precioFinal = helado + precio;
			</script>